config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :courses

  get "/log-in" => 'sessions#new', as: :login
  post "/log-in" => 'sessions#create'
  get "/sign-out" => 'sessions#destroy', as: :signout

end

app/models/course.rb
class Course < ActiveRecord::Base

validates :day_night, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

validates :user_name, presence: true, uniqueness: true
validates :about, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, notice: "Please Log In" if current_user.nil?
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :show, :destroy]
  before_filter :authorize

  def index
    @courses = Course.all.reverse
  end

  def  new
  @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    if @course.destroy
      redirect_to courses_path
    end
  end

  private
  def course_params
    params.require(:course).permit(:title, :day_night)
  end

  def set_course
    @course = Course.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path, notice: "Logged In"
    else
      flass.now.error = "Username or password is invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:update, :edit, :destroy, :show]
before_filter :authorize, except: [:new, :create]
  def index
  @users = User.all.reverse
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @current_user.id == @user.id
      @user.destroy
      redirect_to signout_path
    else
      @user.destroy
      if @user.destroy
        redirect_to users_path
      end
    end
  end

private

def user_params
  params.require(:user).permit(:user_name, :password, :about)
end

def set_user
  @user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :day_night, "Is this course at night?" %>
<%= f.check_box :day_night %>
<% if @course.new_record? %>
  <%= f.submit "Create Course"%>
<% else %>
  <%= f.submit "Update Course" %>
  <%= link_to "Delete Course", course_path(@course), method: :delete %>
<% end %>
<% end %>
<%= link_to "Cancel", users_path %>

app/views/courses/edit.html.erb
<h1> <%= "Edit: #{@course.title}" %> </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<%= link_to "New Course", new_course_path %><br>
<%= link_to "Users", users_path %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Day/Night</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
      <td> <%= link_to course.title, course_path(course) %></td>
      <td> <%if course.day_night == true %>
            Day
            <% else %>
            Night
            <% end %>
      </td>
      <td> <%= link_to "Edit", edit_course_path(course) %></td>
      <td> <%= link_to "Delete", course_path(course), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1> <%= @course.title %> </h1>
<%= link_to "Courses", courses_path %>
<%= link_to "Edit #{@course.title}", edit_course_path(@course) %>
<%= link_to "Delete #{@course.title}", course_path(@course), method: :delete %>

<table>
  <tr>
    <td> <strong> Title:</strong> <%= @course.title %> </td>
    <td> <strong> Night/Day:</strong>
      <%if @course.day_night == true %>
      Day
      <% else %>
      Night
      <% end %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinneganHewittWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# if current_user.nil? %>
<%= link_to "Log In", login_path %>
<%= link_to "Sign up", new_user_path %>
<%# else %>
<%= link_to 'Sign Out', signout_path%>
<%# end %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :user_name %>
<%= f.text_field :user_name %><br>
<%= f.label :about %>
<%= f.text_field :about %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br>
<% if @user.new_record?%>
<%= f.submit %>
<% else %>
<%= f.submit "Update User" %>
<%= link_to "Delete User", user_path(@user), method: :delete %>
<% end %>
<% end %>
<%= link_to "Cancel", users_path %>

app/views/users/edit.html.erb
<h1> <%= "Editing #{@user.user_name}"%> </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All users</h1>
<%= link_to "New User", new_user_path %><br>
<%= link_to "Courses", courses_path %>

<table>
  <thead>
    <tr>
      <th> User Name </th>
      <th> About </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= link_to user.user_name, user_path(user) %></td>
        <td><%=user.about%></td>
        <td> <%= link_to "Edit User", edit_user_path(user) %> </td>
        <td> <%= link_to "Delete User", user_path(user), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.user_name %></h1>
<%= link_to "All Users", users_path %><br>
<%= link_to "Edit #{@user.user_name}", edit_user_path %><br>
<%= link_to "Delete #{@user.user_name}", user_path(@user), method: :delete %>

<table>
  <tr>
    <td> <strong> User Name:</strong> <%= @user.user_name %></td>
  </tr>
  <tr>
    <td> <strong> About:</strong> <%= @user.about %></td>
  </tr>
</table>